#!/bin/sh

[ -r /etc/vconsole.conf.d ] && . /etc/vconsole.conf.d
TTYS=${TTYS:-6}
_index=0
while [ ${_index} -le $TTYS ]; do
    if [ -n "$FONT" ]; then
        setfont ${FONT_MAP:+-m $FONT_MAP} ${FONT_UNIMAP:+-u $FONT_UNIMAP} \
                $FONT -C "/dev/tty${_index}"
    fi
    printf "\033%s" "%G" >/dev/tty${_index}
    _index=$((_index + 1))
done
if [ -n "$KEYMAP" ]; then
    loadkeys -q -u ${KEYMAP}
fi
