#!/bin/sh
[ -r /etc/s6/config/network-detection.conf ] && . /etc/s6/config/network-detection.conf
if [ $SECONDS = 0 ]; then
    SECONDS=60
fi
end=$(( $(date +%s) + $SECONDS ))
while [ $(date +%s) -lt $end ]; do
    default=$(ip route | awk '/^default/{print ($3!="")+($5!="")}')
    if [ "$default" = "2" ]; then
        s6-rc -bu change network
        exit 0
    fi
    # hack to avoid busy looping
    sleep 1
done
exit 1
